### ISSUE TITLE
Missing redirect_to parameter 

### ISSUE THREAD

**Issue by addreas** [jonasdahl/lauset#1]
https://github.com/jonasdahl/lauset/blob/5f53d0349814c44ee4f014a243b46df2a015d3a0/app/routes/hydra/login.tsx#L78

**Comment by jonasdahl** [comment]
Might be return_to as well!

**Comment by addreas** [comment]
Would perhaps be nice to call `redirectToLogin(request, { aal: "aal2" }) `  instead?
